config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  ## Devise routes modifed to match generated folder with scope
  # Admin
   devise_for :admins, path: 'admins', controllers: {
     sessions: "admins/sessions",
     passwords: "admins/passwords",
     registrations: "admins/registrations",
     confirmations: "admins/confirmations"
   }
   # Account
   devise_for :accounts, path: 'accounts', controllers: {
     sessions: "accounts/sessions",
     passwords: "accounts/passwords",
     registrations: "accounts/registrations",
     confirmations: "accounts/confirmations"
   }

  ## Home page
  root "webpages#index"

   ## Customer
   resources :customers do
     # Route to Customer main contact
     get 'main_contact', to: 'customers#main_contact'
     # Route to select a location before creating a machine
     get 'select_location', to: 'customers#select_location'
     resources :locations do
       get 'contact', to: 'locations#contact'
       get 'select_machine_service', to: 'locations#select_machine_service'
       ## Machine
       resources :machines do
         resources :service_calls do
         end
       end
     end
   end
   # Admind dashbord
   resources :adminbords do
     # Route to show account
     collection do
       # collect selected accout locations
       get 'select_account_locations/:account_id', to: 'adminbords#select_account_locations', as: 'select_account_locations'
     end
     # Route to Account Index
     get 'accounts', to: 'adminbords#accounts'
   end
   # Locations
   resources :locations do
     get 'contact', to: 'locations#contact'
     ## Machine
     resources :machines do
       resources :service_calls do
       end
     end
  end
  # Machines
   resources :machines do
     resources :service_calls do
     end
   end
   resources :service_calls do
   end


    ## Stand alone routes
   # Route to select a customer to add a new machine
   get 'select_customer_new_machine', to: 'adminbords#select_customer_new_machine'
   # Route to select a customer to add a new locatiom
   get 'select_customer_new_location', to: 'adminbords#select_customer_new_location'
   # Route to select a customer to add a new account
   get 'select_customer_new_account', to: 'adminbords#select_customer_new_account'
   # Route to show account
   get 'adminbords/show_account_register/:account_id', to: 'adminbords#show_account_register', as: 'show_account_register'


   devise_scope :account do
     get 'accounts/registrations/edit_account_register/:id', to: 'accounts/registrations#edit_account_register', as: 'edit_account_register'
     # Routes to
     put 'accounts/registrations/update_account_register/:id', to: 'accounts/registrations#update_account_register', as: 'update_account_register'
     # Routes to
   end

   # Post accounts locations
   post 'adminbords/save_account/:account_id/locations/:selected_locations_ids', to: 'adminbords#save_account_locations', as: 'save_account_locations'

end

app/models/customer.rb
class Customer < ApplicationRecord

  ## Validation
  validates :customer_number, presence: true
  #validates :bus_name, presence: true
  validates :phone, presence: true

  # kaminari gem
  paginates_per 10

  has_many :locations
  has_many :machines, through: :locations

  has_many :accounts
  has_many :service_calls, through: :accounts
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  ###----- Before actions          Append a callback before actions
  ### condition.before_action if condition is true
  ###  set what actions can be call before using all or some CRUD functions

  before_action :set_customer, only: [:edit, :update, :destroy]

  # select a customer location to add machine
  def select_location
    @customer = Customer.find(params[:customer_id])
    locations = @customer.locations
    @locations = locations.order(:customer_number).page params[:page]
  end
  # main contact customer
  def main_contact
    @customer = Customer.find(params[:customer_id])
  end
  # costumer lists
  def index
    @customers = Customer.order(:customer_number).page params[:page]
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customer_path(@customer)
    else
      flash.now[:notice] = "error"
      render 'new'
    end
  end

  def edit

  end

  def show
    @customer = Customer.find(params[:id])
    locations = @customer.locations
    @locations = locations.order(:customer_number).page params[:page]
  end

  def update
    if @customer.update(customer_params)
      redirect_to customer_path(@customer)
    else
      flash.now[:notice] = "error"
        
      render 'edit'
    end
  end

  def destroy
      @customer.destroy
      redirect_to customers_path
  end

  private

    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:customer_number, :phone, :email, :suite, :street,
        :city, :state, :zip_code, :country,
        :main_contact_title, :main_contact__first_name, :main_contact__last_name,
        :main_contact_phone, :main_contact_email, :bus_name)
    end
end

app/views/customers/_form.html.erb
 <!--
      Form partial
-->

<!--Partial rendered by costumers/edit.html.erb and costumers/new.html.erb-->

<!-- errors management -->
<%  if @customer.errors.any? %>
 <div class="alert alert-danger" role="alert">
   <p><%= pluralize( @customer.errors.count, "error") %> Prevented the costumer's from being submited</p>
   <ul>
     <% @customer.errors.messages.each do |field,errors|  %>
       <% errors.each do |error| %>
         <li> Problems with <%= field %>: <%= error %></li>
       <% end %>
     <% end %>
   </ul>
 </div>
<% end %>

<div class="p-3">
<!-- Buffer Block -->
</div>
<!-- Customer's form, edit/new -->
<%= form_for @customer do |f| %>
<!-- Costumer Number -->
<div class="card w-50 shadow">
  <div class="card-body d-flex flex-row justify-content-between">
    <div><h4 class="pt-3 pr-3"><%= f.label :customer_number, "Customer number" %>:</h4> <%= f.text_field :customer_number,
        class: 'form-control-sm w-75'%> *
    </div>
    <!-- Delete, Admin permission lvl-0 only access-->
    <div>
      <% if @customer.id == nil  %>
        <%= link_to "Delete", root_path, class: 'btn btn-outline-danger disabled'%>
      <% else %>
        <%= link_to "Delete", customer_path(@customer.id), class: 'btn btn-outline-danger', data: {confirm: "Are you sure?"}, method: :delete%>
      <% end %>
    </div>
  </div>
</div>

<!-- Costumer Info -->
<div class="d-flex flex-row shadow"><!-- cards wrapper -->
  <!-- Costumer Name -->
  <div class="card w-50" >
    <h5 class="card-header ">Business name: <%= f.text_field :bus_name, class: "form-control-sm w-50" %> *</h5>
    <!-- Costumer Info -->
    <div class="card-body">
      <div class="d-flex flex-column">
        <!-- Phone and Email -->
        <h4 class="card-title">Contact:</h4>
        <p class="card-text">Tel:&#160;&#160;&#160;&#160;&#160;<%= f.phone_field :phone, class: "form-control-sm" %> *</p>
        <p class="card-text">Email: <%= f.email_field :email, class: "form-control-sm" %></p>
        <p></p>
        <!-- Address -->
        <h4 class="card-title">Address:</h4>
        <p class="card-text "><%= f.text_field :suite, placeholder:"suite",class: "form-control-sm w-25" %></p>
        <p class="card-text "><%= f.text_field :street, placeholder:"street", class: "form-control-sm w-100" %></p>
        <p class="card-text "><%= f.text_field :city, placeholder:"city", class: "form-control-sm w-50" %></p>
        <p class="card-text "><%= f.text_field :state, placeholder:"state", class: "form-control-sm w-50" %></p>
        <p class="card-text "><%= f.text_field :zip_code, placeholder:"zip code", class: "form-control-sm w-25" %></p>
        <p class="card-text "><%= f.text_field :country, placeholder:"country", class: "form-control-sm w-50" %></p>
      </div>
    </div><!-- card-body -->
    <!-- Submit, Admin permission lvl-1 or lower, access-->
    <!-- On Submit link to 'POST' customers#create -->
    <%= f.submit "Submit", class: "btn btn-info" %>
</div><!-- card -->
<!-- Main Contact Infomation -->
  <% if @customer.main_contact_email != nil %>
    <!-- Main Contact does exist -->
    <!-- Main Contact Infomation -->
    <div class="card w-50 cardSizing">
      <div class="card-header d-flex justify-content-between">
        <h5>Main Contact</h5>
      </div>
      <div class="card-body">
        <!-- Name -->
        <div class="d-flex flex-row justify-content-between">
          <div>
            <p class="card-text"><strong>Title:&#160;</strong><%= @customer.main_contact_title %></p>
            <p class="card-text"><strong>First name:&#160;</strong><%= @customer.main_contact__first_name %></p>
            <p class="card-text"><strong>Last name:&#160;</strong><%= @customer.main_contact__last_name %></P>
          </div>
          <!-- Phone and email -->
          <div class="mr-3">
            <p class="card-text"></p>
            <p class="card-text"><strong>Tel:&#160;</strong><%= @customer.main_contact_phone %></p>
            <p class="card-text"><strong>Email:&#160;</strong>&#160;<%= @customer.main_contact_email %></p>
        </div>
      </div><!-- card-body -->
    </div><!-- card -->
    <!-- Edit, Admin permission lvl-1 or lower, access-->
    <%# if customer exists, link to the customer main contact partial edit %>
    <% if @customer.customer_number != nil %>
      <%= link_to "Edit", customer_main_contact_path(@customer), class: 'btn btn-info'%>
    <% end %>
  <% else %>
    <!-- Main Contact does not exist -->
    <div class="card w-50 cardSizing">
      <!--  No main contact partial -->
      <%= render  'noMainContact' %>
      <!-- Add, Admin permission lvl-1 or lower, access-->
      <!-- checks if contact exist for edit rendering, if yes it disables add link -->
      <% if @customer.customer_number != nil and @customer.main_contact_email == nil %>
        <%= link_to "Add", customer_main_contact_path(@customer), class: 'btn btn-info mt-0' %>
      <% else %>
        <%= link_to "Add", root_path, class: "btn btn-info mt-0 disabled" %>
      <% end %>
    </div><!-- card -->
  <% end %>
<% end %>
</div><!-- cards wrapper -->

app/views/customers/_noMainContact.html.erb
<!--
      No Main Contact exist partial
-->

<!--Partial rendered by costumers/_form.html.erb and costumers/show.html.erb-->

<h5 class="card-header">No main contact</h5>
<div class="card-body">
  <div class="d-flex flex-row justify-content-between">
    <div>
      <p class="card-text m-0">Title: </p>
      <p class="card-text m-0">First name: </p>
      <p class="card-text m-0">Last name: </p>
      <p></p>
      <p class="card-text m-0">Tel: </p>
      <p class="card-text m-0">Email: </p>
    </div>
  </div>
</div>

app/views/customers/edit.html.erb
<!--
            Admins with permissions lvl-1 or lower are allower to access this page, customer-no
-->

<!--
Form Customer Edit
edits the customer information and lists all the contacts, location and machines
 -->

<h3 class="card-header shadow-sm">Customer Edit</h3>

<%= render 'form' %>

app/views/customers/index.html.erb
<div class="p-3">
<!-- Buffer Block -->
</div>
<h1 class="card-header shadow-sm">Customer Index</h1>
<%= paginate @customers %>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.customer_number %></td>
      <td><%= customer.bus_name %></td>
      <td><%= customer.phone %></td>
      <td><%= customer.email %></td>
      <td><%= link_to "Show", customer_path(customer),
        class: "btn-sm btn-info mt-2  p-1"%></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @customers %>

app/views/customers/main_contact.html.erb
<!--
            Admins with permissions lvl-2 or lower are allower to access this page, customer-no
-->

<!--
Form Customer Information
list all the customer information contacts, location and machines
 -->
 <div class="p-3">
 <!-- Buffer Block -->
 </div>
<h3 class="card-header shadow-sm">Main Contact</h3>

<!-- Customer form, show -->
<%= form_for @customer do |f| %>
  <div class="p-3">
  <!-- Buffer Block -->
  </div>

  <!-- Costumer Number and delete button -->
  <div class="card w-50">
    <div class="card-body d-flex flex-row justify-content-between">
      <h5>Customer: <%= @customer.customer_number %></h5>
      <!-- Delete, Admin permission lvl-0 only access-->
      <div>
        <%= link_to "Delete", customer_path(@customer), class: 'btn btn-outline-danger', data: {confirm: "Are you sure?"}, method: :delete%>
      </div>
    </div>
  </div>
  <!-- Costumer Name -->
  <div class="d-flex flex-row shadow"> <!-- cards wrapper -->
    <div class="card w-50">
      <h5 class="card-header"><%= @customer.bus_name %></h5>
      <!-- Costumer Info -->
      <div class="card-body">
        <div class="d-flex flex-row justify-content-between">
          <!-- Phone and Email -->
          <div>
            <h5 class="card-title">Contact:</h5>
            <p class="card-text m-0">Tel: <%= @customer.phone %></p>
            <p class="card-text m-0">Email: <%= @customer.email %></p>
          </div>
          <!-- Address -->
          <div class="mr-3">
            <h5 class="card-title">Address:</h5>
            <p class="card-text d-flex justify-content-end m-0"><%= @customer.suite %></p>
            <p class="card-text d-flex justify-content-end m-0"><%= @customer.street %></p>
            <p class="card-text d-flex justify-content-end m-0"><%= @customer.city%>, <%= @customer.state%> <%= @customer.zip_code %></p>
            <p class="card-text d-flex justify-content-end m-0"><%= @customer.country %></p>
          </div>
        </div>
      </div><!-- card-body -->
      <!-- On Edit link to 'GET' customers#edit -->
      <%= link_to "Edit", edit_customer_path(@customer), class: 'btn btn-info' %>
    </div><!-- card -->
    <!-- Main Contact -->
    <div class="card w-50 h-75">
      <div class="card-header formHeadBlockSizing">
        <h5>Main Contact</h5>
      </div>
      <div class="card-body">
        <div class="d-flex flex-row justify-content-between">
          <!-- Name -->
          <div>
            <p class="card-text m-0">Title:<p>
            <p class="card-text"><%= f.text_field :main_contact_title, class: 'form-control-sm' %></p>
            <p class="card-text"><%= f.text_field :main_contact__first_name, placeholder:"First name", class: 'form-control-sm' %></p>
            <p class="card-text"><%= f.text_field :main_contact__last_name, placeholder:"Last name", class: 'form-control-sm' %></P>
          </div>
          <!-- Phone and email -->
          <div class="mr-5">
            <p class="card-text"></p>
            <p class="card-text m-0">Tel:</p>
            <p class="card-text"><%= f.text_field :main_contact_phone, class: 'form-control-sm'  %></p>
            <p class="card-text m-0">Email:</p>
            <p class="card-text"><%= f.text_field :main_contact_email, class: 'form-control-sm' %></p>
          </div>
        </div>
      </div><!-- card-body -->
      <!-- Edit, Admin permission lvl-1 or lower, access-->
      <!-- On Edit link to 'PUT' customers#update -->
      <%= f.submit "Submit", class: "btn btn-info" %>
    </div><!-- card -->
  </div><!-- cards wrapper -->
<% end %>

app/views/customers/new.html.erb
<!--
            Admins with permissions lvl-1 or lower are allower to access this page, customer-no
-->

<!--
Form Customer Registration
registers the customer
 -->
 <div class="p-3">
 <!-- Buffer Block -->
 </div>
<h3 class="card-header shadoe-sm">Customer  Registration</h3>

<%= render 'form' %>

app/views/customers/select.html.erb
<h3 class="card-header"> Select a location</h3>
<div class="p-3">
<!-- Buffer Block -->
</div>
<%= paginate @locations %>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Customer's number</th>
      <th scope="col">Costomer's name</th>
      <th scope="col">Location's name</th>
      <th scope="col">Contact' name</th>
      <th scope="col">Contac's phone</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @locations.each do |location| %>
    <tr>
      <td><%= location.customer_number %></td>
      <td><%= location.customer.name %></td>
      <td><%= location.name %></td>
      <td><%= location.contact__first_name %></td>
      <td><%= location.contact_phone%></td>
      <td><%= link_to "Select",new_customer_location_machine_path(location.customer, location),class: "btn-sm btn-info  mt-2  p-1"%></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @locations %>

app/views/customers/select_location.html.erb
<!--
            Admins with permissions lvl-1 or lower are allower to access this page, customer-no
-->

<!--
select locationto create a new machine
list all the customer information contacts, location and machines
 -->
 <div class="p-3">
 <!-- Buffer Block -->
 </div>
<h3 class="card-header shadow-sm">Select a location</h3>
<div class="p-3">
<!-- Buffer Block -->
</div>
<%= paginate @locations %>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Customer#</th>
      <th scope="col">Costomer Name</th>
      <th scope="col">Location Name</th>
      <th scope="col">Contact</th>
      <th scope="col">Phone</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @locations.each do |location| %>
    <tr>
      <td><%= location.customer_number %></td>
      <td><%= location.customer.bus_name %></td>
      <td><%= location.name %></td>
      <td><%= location.contact__first_name %></td>
      <td><%= location.contact_phone%></td>
      <td><%= link_to "Select",new_customer_location_machine_path(location.customer, location),class: "btn-sm btn-info  mt-2  p-1"%></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @locations %>

app/views/customers/show.html.erb
<!--
            Admins with permissions lvl-2 or lower are allower to access this page, customer-no
-->

<!--
Form Customer Information
list all the customer information contacts, location and machines
 -->
 <div class="p-3">
 <!-- Buffer Block -->
 </div>
<h3 class="card-header shadow-sm">Customer Information</h3>
<div class="p-3">
<!-- Buffer Block -->
</div>
<!-- Customer form, show -->
<!-- Costumer Number and delete button -->
<div class="card w-50 shadow">
  <div class="card-body d-flex flex-row justify-content-between">
    <h5>Customer: <%= @customer.customer_number %></h5>
    <!-- Delete, Admin permission lvl-0 only access-->
    <div>
      <%= link_to "Delete", customer_path(@customer), class: 'btn btn-outline-danger', data: {confirm: "Are you sure?"}, method: :delete%>
    </div>
  </div>
</div>
<!-- Costumer Name -->
<div class="d-flex flex-row shadow"> <!-- cards wrapper -->
  <div class="card w-50">
    <h5 class="card-header"><%= @customer.bus_name %></h5>
    <!-- Costumer Info -->
    <div class="card-body">
      <div class="d-flex flex-row justify-content-between">
        <!-- Phone and Email -->
        <div>
          <h5 class="card-title">Contact:</h5>
          <p class="card-text m-0">Tel: <%= @customer.phone %></p>
          <p class="card-text m-0">Email: <%= @customer.email %></p>
        </div>
        <!-- Address -->
        <div class="mr-3">
          <h5 class="card-title">Address:</h5>
          <p class="card-text d-flex justify-content-end m-0"><%= @customer.suite %></p>
          <p class="card-text d-flex justify-content-end m-0"><%= @customer.street %></p>
          <p class="card-text d-flex justify-content-end m-0"><%= @customer.city%>, <%= @customer.state%> <%= @customer.zip_code %></p>
          <p class="card-text d-flex justify-content-end m-0"><%= @customer.country %></p>
        </div>
      </div>
      <div>
        <%= link_to "Add a location", new_customer_location_path(@customer), class: "btn btn-outline-primary" %>
        <%= link_to "Add a machine", customer_select_location_path(@customer), class: "btn btn-outline-success ml-5" %>
      </div>
    </div><!-- card-body -->
    <!-- On Edit link to 'GET' customers#edit -->
    <%= link_to "Edit", edit_customer_path(@customer), class: 'btn btn-info' %>
  </div><!-- card -->
  <!-- Main Contact Infomation -->
  <% if @customer.main_contact_email != nil %>
    <!-- Main Contact does exist -->
    <!-- Main Contact Infomation -->
    <div class="card w-50">
      <div class="card-header d-flex justify-content-between">
        <h5>Main Contact</h5>
      </div>

      <div class="card-body">
        <!-- Name -->
          <div class="d-flex flex-row justify-content-between">
            <div>
              <p class="card-text"><strong>Title:&#160;</strong><%= @customer.main_contact_title %></p>
              <p class="card-text"><strong>First name:&#160;</strong><%= @customer.main_contact__first_name %></p>
              <p class="card-text"><strong>Last name:&#160;</strong><%= @customer.main_contact__last_name %></P>
            </div>
            <!-- Phone and email -->
            <div class="mr-3">
              <p class="card-text"></p>
              <p class="card-text"><strong>Tel:&#160;</strong><%= @customer.main_contact_phone %></p>
              <p class="card-text"><strong>Email:&#160;</strong> <%= @customer.main_contact_email %></p>
          </div>
        </div>
      </div><!-- card-body -->
      <!-- Edit, Admin permission lvl-1 or lower, access-->
      <!-- On Edit link to 'GET' customers#edit -->
      <%= link_to "Edit", customer_main_contact_path(@customer.id), class: 'btn btn-info'%>
    </div><!-- card -->
  <% else %>
    <!-- Main Contact does not exist -->
    <div class="card w-50">
      <!--  No main contact partial -->
      <%= render  'noMainContact' %>
      <!-- Add, Admin permission lvl-1 or lower, access-->
      <%= link_to "Add", customer_main_contact_path(@customer.id), class: "btn btn-info mt-0" %>
    </div><!-- card -->
  <% end %>
</div><!-- cards wrapper -->

<div class="p-3">
<!-- Buffer Block -->
</div>
<!-- locations -->
<h3 class="card-header shadow-sm">Locations</h3>
<%= paginate @locations %>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Number</th>
      <th scope="col">Customer Name</th>
      <th scope="col">Location Name</th>
      <th scope="col">Contact</th>
      <th scope="col">Phone</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @locations.each do |location| %>
    <tr>
      <td><%= location.customer_number %></td>
      <td><%= location.customer.bus_name %></td>
      <td><%= location.name %></td>
      <td><%= location.contact__first_name %></td>
      <td><%= location.contact_phone%></td>
      <td><%= link_to "Show", location_path(location),
        class: "btn-sm btn-info  mt-2  p-1"%></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @locations %>

<!-- Machines -->
<h3 class="card-header">Machines</h3>
<%= paginate @locations %>
<% @locations.each do |location| %>
<h6 class="card-header shadow-sm">Location: <%= location.name %></h6>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Number</th>
      <th scope="col">Customer Name</th>
      <th scope="col">Number</th>
      <th scope="col">Model</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% location.machines.each do |machine| %>
    <tr>
      <td><%= location.customer_number %></td>
      <td><%= location.customer.bus_name %></td>
      <td><%= machine.machine_number%></td>
      <td><%= machine.model%></td>
      <td><%= link_to "Show", machine_path(machine),
        class: "btn-sm btn-info  mt-2  p-1"%></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>
<%= paginate @locations %>