config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  ## Devise routes modifed to match generated folder with scope
  # Admin
   devise_for :admins, path: 'admins', controllers: {
     sessions: "admins/sessions",
     passwords: "admins/passwords",
     registrations: "admins/registrations",
     confirmations: "admins/confirmations"
   }
   # Account
   devise_for :accounts, path: 'accounts', controllers: {
     sessions: "accounts/sessions",
     passwords: "accounts/passwords",
     registrations: "accounts/registrations",
     confirmations: "accounts/confirmations"
   }

  ## Home page
  root "webpages#index"

   ## Customer
   resources :customers do
     # Route to Customer main contact
     get 'main_contact', to: 'customers#main_contact'
     # Route to select a location before creating a machine
     get 'select_location', to: 'customers#select_location'
     resources :locations do
       get 'contact', to: 'locations#contact'
       get 'select_machine_service', to: 'locations#select_machine_service'
       ## Machine
       resources :machines do
         resources :service_calls do
         end
       end
     end
   end
   # Admind dashbord
   resources :adminbords do
     # Route to show account
     collection do
       # collect selected accout locations
       get 'select_account_locations/:account_id', to: 'adminbords#select_account_locations', as: 'select_account_locations'
     end
     # Route to Account Index
     get 'accounts', to: 'adminbords#accounts'
   end
   # Locations
   resources :locations do
     get 'contact', to: 'locations#contact'
     ## Machine
     resources :machines do
       resources :service_calls do
       end
     end
  end
  # Machines
   resources :machines do
     resources :service_calls do
     end
   end
   resources :service_calls do
   end


    ## Stand alone routes
   # Route to select a customer to add a new machine
   get 'select_customer_new_machine', to: 'adminbords#select_customer_new_machine'
   # Route to select a customer to add a new locatiom
   get 'select_customer_new_location', to: 'adminbords#select_customer_new_location'
   # Route to select a customer to add a new account
   get 'select_customer_new_account', to: 'adminbords#select_customer_new_account'
   # Route to show account
   get 'adminbords/show_account_register/:account_id', to: 'adminbords#show_account_register', as: 'show_account_register'


   devise_scope :account do
     get 'accounts/registrations/edit_account_register/:id', to: 'accounts/registrations#edit_account_register', as: 'edit_account_register'
     # Routes to
     put 'accounts/registrations/update_account_register/:id', to: 'accounts/registrations#update_account_register', as: 'update_account_register'
     # Routes to
   end

   # Post accounts locations
   post 'adminbords/save_account/:account_id/locations/:selected_locations_ids', to: 'adminbords#save_account_locations', as: 'save_account_locations'

end

app/models/machine.rb
class Machine < ApplicationRecord
  ## Validation
  validates :customer_number, presence: true


  # kaminari gem
  paginates_per 10

  belongs_to :location
  has_many :service_calls
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController

    ###----- Before actions          Append a callback before actions
    ### condition.before_action if condition is true
    ###  set what actions can be call before using all or some CRUD functions

    before_action :set_machine, only: [:edit, :update, :destroy, :show]

    def index
      @machines = Machine.order(:machine_number).page params[:page]
    end

    def new
      @location = Location.find(params[:location_id])
      @machine = Machine.new
    end

    def create
        @machine = Machine.new(machine_params)
        @machine.save
        if @machine.customer_number == nil
          flash.now[:notice] = "error"
          render 'new'
        else
          redirect_to machine_path(@machine)
        end
    end

    def edit

    end

    def show
      @service_calls = []
      ServiceCall.all.each do |service|
        if service.machine  == @machine
          @service_calls << service
        end
      end
    end

    def update
      if @machine.update(machine_params)

        redirect_to machine_path(@machine)
      else
        flash.now[:notice] = "error"
        render 'edit'
      end
    end

    def destroy
        @machine.destroy
        redirect_to locations_path
    end

    private

      def set_machine
        @machine = Machine.find(params[:id])
      end

      def machine_params
        params.require(:machine).permit(:customer_number, :machine_number,
          :model, :serial_number, :on_location, :location_id)
      end
end

app/views/machines/_form.html.erb
<!--
      Form partial
-->

<!--Partial rendered by locations/edit.html.erb and costumers/new.html.erb-->

<!-- errors management -->
<%  if @machine.errors.any? %>
 <div class="alert alert-danger" role="alert">
   <p><%= pluralize( @machine.errors.count, "error") %> Prevented the machine's from being submited</p>
   <ul>
     <% @machine.errors.messages.each do |field,errors|  %>
       <% errors.each do |error| %>
         <li> Problems with <%= field %>: <%= error %></li>
       <% end %>
     <% end %>
   </ul>
 </div>
<% end %>

<div class="p-3">
<!-- Buffer Block -->
</div>

<!-- Customer Number name phone -->
<div class="card w-50 shadow">
  <div class="card-body d-flex flex-row justify-content-between ">
    <div>
      <div>
        <h6 class="pt-3 pr-3"><%= @location.customer.bus_name %></h6>
        <h6 class="pt-3 pr-3">Location:&#160;<%= @location.name%></h6>
        <h6 class="pt-3 pr-3">Tel:&#160;<%= @location.phone%></h6>
      </div>
    </div>
    <div>
      <h6 class="pt-3 pr-3">Customer number: <%= @location.customer_number %></h6>
    </div>
  </div>
</div>

<%= form_for @machine do |f| %>
<!--machines Info -->
  <div class="d-flex flex-row shadow"><!-- cards wrapper -->
    <!-- machines Name -->
    <div class="card w-50" >
      <div class="card-header d-flex flex-row justify-content-between">
        <h5 >Machines number:&#160;<%= f.text_field :machine_number, class: "form-control-sm mt-1" %> *</h5>
        <div>
          <% if @machine.machine_number == nil  %>
            <%= link_to "Delete", machines_path(@machine), class: 'btn btn-outline-danger disabled', data: {confirm: "Are you sure?"}, method: :delete %>
          <% else %>
            <%= link_to "Delete", machines_path(@machine), class: 'btn btn-outline-danger', data: {confirm: "Are you sure?"}, method: :delete %>
          <% end %>
        </div>
      </div>
      <div class="card-body">
        <div class="d-flex flex-column">
          <p class="card-text">Model:&#160;&#160;&#160;&#160;<%= f.text_field :model, class: "form-control-sm" %></p>
          <p class="card-text">Serial#:&#160;<%= f.text_field :serial_number, class: "form-control-sm w-75" %></p>
          <p></p>
          <!-- Address -->
          <h4 class="card-title">Machine location on site:</h4>
          <p class="card-text "><%= f.text_field :on_location, placeholder:"On location",class: "form-control-sm w-100" %></p>
        </div>
        <!-- data params to pass submitted along with form-->
        <%= f.hidden_field :customer_number, value: @location.customer_number%>
        <%= f.hidden_field :location_id, value: @location.id %>
      </div><!-- card-body -->

      <!-- Submit, Admin permission lvl-1 or lower, access-->
      <%= f.submit "Submit", class: "btn btn-info"%>
    </div><!-- card -->
    <% end %>
    <!-- Contact Infomation -->
    <% if @location.contact_email != nil %>
      <!-- Contact does exist -->
      <!-- Contact Infomation -->
      <div class="card w-50 cardSizing">
        <div class="card-header d-flex justify-content-between">
          <h5>Location contact</h5>
        </div>
        <div class="card-body">
          <!-- Name -->
          <div class="d-flex flex-row justify-content-between">
            <div>
              <p class="card-text"><strong>Title:&#160;</strong><%= @location.contact_title %></p>
              <p class="card-text"><strong>First name:&#160;</strong><%= @location.contact__first_name %></p>
              <p class="card-text"><strong>Last name:&#160;</strong><%= @location.contact__last_name %></P>
            </div>
            <!-- Phone and email -->
            <div class="mr-3">
              <p class="card-text"></p>
              <p class="card-text"><strong>Tel:&#160;</strong><%= @location.contact_phone %></p>
              <p class="card-text"><strong>Email:&#160;</strong><%= @location.contact_email %></p>
          </div>
        </div><!-- card-body -->
      </div><!-- card -->
      <!-- Edit, Admin permission lvl-1 or lower, access-->
      <%# if location exists, link to the location contact partial edit %>
      <% if @location.customer.bus_name != nil %>
        <%= link_to "Edit", location_contact_path(@location), class: 'btn btn-info'%>
      <% end %>
    <% else %>
        <!-- Contact does not exist -->
        <div class="card w-50 cardSizing">
          <!--  contact partial -->
          <%= render  'noContact' %>
          <!-- Add, Admin permission lvl-1 or lower, access-->
          <!-- checks if contact exist for edit rendering, if yes it disables add link -->
          <% if @location.customer.bus_name != nil and @location.contact_email == nil %>
              <%= link_to "Add", location_contact_path(@location), class: 'btn btn-info mt-0' %>
          <% else %>
            <%= link_to "Add", root_path, class: "btn btn-info mt-0 disabled" %>
          <% end %>
        </div><!-- card -->
    <% end %>

  </div><!-- cards wrapper -->

app/views/machines/_noContact.html.erb
<!--
      No Main Contact exist partial
-->

<!--Partial rendered by costumers/_form.html.erb and costumers/show.html.erb-->

<h5 class="card-header">No location contact</h5>
<div class="card-body">
  <div class="d-flex flex-row justify-content-between">
    <div>
      <p class="card-text m-0">Title: </p>
      <p class="card-text m-0">First name: </p>
      <p class="card-text m-0">Last name: </p>
      <p></p>
      <p class="card-text m-0">Tel: </p>
      <p class="card-text m-0">Email: </p>
    </div>
  </div>
</div>

app/views/machines/edit.html.erb
<!--
            Admins with permissions lvl-1 or lower are allower to access this page, customer-no
-->

<!--
Form Customer Edit
edits the customer information and lists all the contacts, location and machines
 -->

<h3 class="card-header shadow-sm">Machine Edit</h3>

<!-- errors management -->
<%  if @machine.errors.any? %>
 <div class="alert alert-danger" role="alert">
   <p><%= pluralize( @machine.errors.count, "error") %> Prevented the machine's from being submited</p>
   <ul>
     <% @machine.errors.messages.each do |field,errors|  %>
       <% errors.each do |error| %>
         <li> Problems with <%= field %>: <%= error %></li>
       <% end %>
     <% end %>
   </ul>
 </div>
<% end %>

<div class="p-3">
<!-- Buffer Block -->
</div>

<!-- Machine's form, edit/new -->

<!-- Customer Number name phone -->
<div class="card w-50 shadow">
  <div class="card-body d-flex flex-row justify-content-between ">
    <div>
      <div>
        <h6 class="pt-3 pr-3"><%= @machine.location.customer.bus_name %></h6>
        <h6 class="pt-3 pr-3">Location:&#160;<%= @machine.location.name%></h6>
        <h6 class="pt-3 pr-3">Tel:&#160;<%= @machine.location.phone%></h6>
      </div>
    </div>
    <div>
      <h6 class="pt-3 pr-3">Customer number: <%= @machine.location.customer_number %></h6>
    </div>
  </div>
</div>

<%= form_for @machine do |f| %>
<!--machines Info -->
  <div class="d-flex flex-row shadow"><!-- cards wrapper -->
    <!-- machines Name -->
    <div class="card w-50" >
      <div class="card-header d-flex flex-row justify-content-between">
        <h5 >Machines number:&#160;<%= f.text_field :machine_number, class: "form-control-sm mt-1" %> *</h5>
        <div>
          <% if @machine.machine_number == nil  %>
            <%= link_to "Delete", machines_path(@machine), class: 'btn btn-outline-danger disabled', data: {confirm: "Are you sure?"}, method: :delete %>
          <% else %>
            <%= link_to "Delete", machines_path(@machine), class: 'btn btn-outline-danger', data: {confirm: "Are you sure?"}, method: :delete %>
          <% end %>
        </div>
      </div>
      <div class="card-body">
        <div class="d-flex flex-column">
          <p class="card-text">Model:&#160;&#160;&#160;&#160;<%= f.text_field :model, class: "form-control-sm" %></p>
          <p class="card-text">Serial#:&#160;<%= f.text_field :serial_number, class: "form-control-sm w-75" %></p>
          <p></p>
          <!-- Address -->
          <h4 class="card-title">Machine location on site:</h4>
          <p class="card-text "><%= f.text_field :on_location, placeholder:"On location",class: "form-control-sm w-100" %></p>
        </div>
        <!-- data params to pass submitted along with form-->
        <%= f.hidden_field :customer_number, value: @machine.customer_number%>
        <%= f.hidden_field :location_id, value: @machine.location.id %>
      </div><!-- card-body -->

      <!-- Submit, Admin permission lvl-1 or lower, access-->
      <%= f.submit "Submit", class: "btn btn-info"%>
    </div><!-- card -->
    <% end %>
    <!-- Contact Infomation -->
    <% if @machine.location.contact_email != nil %>
      <!-- Contact does exist -->
      <!-- Contact Infomation -->
      <div class="card w-50 cardSizing">
        <div class="card-header d-flex justify-content-between">
          <h5>Location contact</h5>
        </div>
        <div class="card-body">
          <!-- Name -->
          <div class="d-flex flex-row justify-content-between">
            <div>
              <p class="card-text"><strong>Title:&#160;</strong><%= @machine.location.contact_title %></p>
              <p class="card-text"><strong>First name:&#160;</strong><%= @machine.location.contact__first_name %></p>
              <p class="card-text"><strong>Last name:&#160;</strong><%= @machine.location.contact__last_name %></P>
            </div>
            <!-- Phone and email -->
            <div class="mr-3">
              <p class="card-text"></p>
              <p class="card-text"><strong>Tel:&#160;</strong><%= @machine.location.contact_phone %></p>
              <p class="card-text"><strong>Email:&#160;</strong><%= @machine.location.contact_email %></p>
          </div>
        </div><!-- card-body -->
      </div><!-- card -->
      <!-- Edit, Admin permission lvl-1 or lower, access-->
      <%# if location exists, link to the location contact partial edit %>
      <% if @machine.location.customer.bus_name != nil %>
        <%= link_to "Edit", location_contact_path(@machine.location), class: 'btn btn-info'%>
      <% end %>
    <% else %>
        <!-- Contact does not exist -->
        <div class="card w-50 cardSizing">
          <!--  contact partial -->
          <%= render  'noContact' %>
          <!-- Add, Admin permission lvl-1 or lower, access-->
          <!-- checks if contact exist for edit rendering, if yes it disables add link -->
          <% if @machine.location.customer.bus_name != nil and @machine.location.contact_email == nil %>
              <%= link_to "Add", location_contact_path(@machine.location), class: 'btn btn-info mt-0' %>
          <% else %>
            <%= link_to "Add", root_path, class: "btn btn-info mt-0 disabled" %>
          <% end %>
        </div><!-- card -->
    <% end %>

  </div><!-- cards wrapper -->

app/views/machines/index.html.erb
  <h1 class="card-header shadow-sm">Machine Index</h1>
  <%= paginate @machines %>
  <table class="table">
    <thead class="thead-light text-sm">
      <tr>
        <th scope="col">Customer#</th>
        <th scope="col">Location Name</th>
        <th scope="col">Location</th>
        <th scope="col">Number</th>
        <th scope="col">Model</th>
        <th scope="col">Contact</th>
        <th scope="col">Phone</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= machine.customer_number %></td>
        <td><%= machine.location.customer.bus_name %></td>
        <td><%= machine.location.name %></td>
        <td><%= machine.machine_number %></td>
        <td><%= machine.model %></td>
        <td><%= machine.location.contact__first_name %></td>
        <td><%= machine.location.contact_phone%></td>
        <td><%= link_to "Show", machine_path(machine),
          class: "btn-sm btn-info  mt-2  p-1" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @machines %>

app/views/machines/new.html.erb
<!--
            Admins with permissions lvl-1 or lower are allower to access this page, customer-no
-->

<!--
Form Machine Registration
 -->

<h3 class="card-header shadow-sm">Machine  Registration</h3>

<%= render 'form' %>

app/views/machines/show.html.erb
<!--
Admins with permissions lvl-2 or lower are allower to access this page, customer-no
-->

<!--
Machine Information
list all the machine information contacts and location
-->
<div class="p-3">
<!-- Buffer Block -->
</div>
<h3 class="card-header shadow-sm">Machine Information</h3>

<div class="p-3">
<!-- Buffer Block -->
</div>
<!-- Customer Number name phone -->
<div class="card w-50 shadow">
  <div class="card-body d-flex flex-row justify-content-between ">
    <div>
      <div>
        <h6 class="pt-3 pr-3"><%= @machine.location.customer.bus_name %></h6>
        <h6 class="pt-3 pr-3">Location:&#160;<%= @machine.location.name%></h6>
        <h6 class="pt-3 pr-3">Tel:&#160;&#160;&#160;&#160;&#160;&#160;<%= @machine.location.phone%></h6>
      </div>
    </div>
    <div>
      <h6 class="pt-3 pr-3"><%= @machine.customer_number %></h6>
      <%= link_to "Show", customer_path(@machine.location.customer), class: "btn btn-outline-secondary mt-5" %>
    </div>
  </div>
</div>
<!--Machine Info -->
<div class="d-flex flex-row shadow"> <!-- cards wrapper -->
  <div class="card w-50">
    <div class="card-header d-flex flex-row justify-content-between">
      <h5 class="mt-2">Number: <%= @machine.machine_number %></h5>
      <div>
        <%= link_to "Delete", machine_path(@machine), class: 'btn btn-outline-danger', data: {confirm: "Are you sure?"}, method: :delete%>
      </div>
    </div>
    <!-- Machine Info -->
    <div class="card-body">
      <div class="d-flex flex-row justify-content-between">
        <!-- Phone and Email -->
        <div>
          <h5 class="card-title">Machine</h5>
          <p class="card-text m-0">Model:&#160;&#160;&#160;&#160;<%= @machine.model %></p>
          <p class="card-text m-0">Seriall#:&#160;<%= @machine.serial_number %></p>
          <p class="card-text m-0">location:&#160;<%= @machine.on_location %></p>
        </div>
        <!-- Address -->
        <div class="mr-3">
          <h5 class="card-title">Address:</h5>
          <p class="card-text d-flex justify-content-end m-0"><%= @machine.location.suite %></p>
          <p class="card-text d-flex justify-content-end m-0"><%= @machine.location.street %></p>
          <p class="card-text d-flex justify-content-end m-0"><%= @machine.location.city%>, <%= @machine.location.state%> <%= @machine.location.zip_code %></p>
          <p class="card-text d-flex justify-content-end m-0"><%= @machine.location.country %></p>
        </div>
      </div>
        <%= link_to "Add a location", new_customer_location_path(@machine.location.customer), class: "btn btn-outline-primary mt-5" %>
        <%= link_to "Add machine", new_customer_location_machine_path(@machine.location.customer, @machine.location), class: "ml-5  btn btn-outline-info mt-5" %>
    </div><!-- card-body -->
    <%= link_to "Edit", edit_machine_path(@machine), class: 'btn btn-info' %>
  </div><!-- card -->
  <!-- Contact Infomation -->
  <% if @machine.location.contact_email != nil %>
    <!-- Contact does exist -->
    <!-- Contact Infomation -->
    <div class="card w-50">
      <div class="card-header d-flex justify-content-between">
        <h5>Contact</h5>
      </div>

      <div class="card-body">
        <!-- Name -->
          <div class="d-flex flex-row justify-content-between">
            <div>
              <p class="card-text"><strong>Title:&#160;</strong><%= @machine.location.contact_title %></p>
              <p class="card-text"><strong>First name:&#160;</strong><%= @machine.location.contact__first_name %></p>
              <p class="card-text"><strong>Last name:&#160;</strong><%= @machine.location.contact__last_name %></P>
            </div>
            <!-- Phone and email -->
            <div class="mr-3">
              <p class="card-text"></p>
              <p class="card-text"><strong>Tel:&#160;</strong><%= @machine.location.contact_phone %></p>
              <p class="card-text"><strong>Email:&#160;</strong> <%= @machine.location.contact_email %></p>
          </div>
        </div>
      </div><!-- card-body -->
      <!-- Edit, Admin permission lvl-1 or lower, access-->
      <%= link_to "Edit", location_contact_path(@machine.location), class: 'btn btn-info'%>
    </div><!-- card -->
  <% else %>
    <!-- Contact does not exist -->
    <div class="card w-50">
      <!--  contact partial -->
      <%= render  'noContact' %>
      <!-- Add, Admin permission lvl-1 or lower, access-->
      <%= link_to "Add", location_contact_path(@machine.location), class: "btn btn-info mt-0" %>
    </div><!-- card -->
  <% end %>
</div><!-- cards wrapper -->
<div class="p-3">
<!-- Buffer Block -->
</div>
<h4 class="card-header shasw-sm">Service Call</h4>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Costumer#</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @service_calls.each do |service| %>
    <tr>
      <td><%= service.customer_number %></td>
      <td><%= service.account.first_name%></td>
      <td><%= service.account.last_name%></td>
      <td><%= service.account.last_name%></td>
      <td><%= link_to "Show", service_call_path(service),
        class: "btn-sm btn-info  mt-2  p-1"%></td>
    </tr>
    <% end %>
  </tbody>
</table>