config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  ## Devise routes modifed to match generated folder with scope
  # Admin
   devise_for :admins, path: 'admins', controllers: {
     sessions: "admins/sessions",
     passwords: "admins/passwords",
     registrations: "admins/registrations",
     confirmations: "admins/confirmations"
   }
   # Account
   devise_for :accounts, path: 'accounts', controllers: {
     sessions: "accounts/sessions",
     passwords: "accounts/passwords",
     registrations: "accounts/registrations",
     confirmations: "accounts/confirmations"
   }

  ## Home page
  root "webpages#index"

   ## Customer
   resources :customers do
     # Route to Customer main contact
     get 'main_contact', to: 'customers#main_contact'
     # Route to select a location before creating a machine
     get 'select_location', to: 'customers#select_location'
     resources :locations do
       get 'contact', to: 'locations#contact'
       get 'select_machine_service', to: 'locations#select_machine_service'
       ## Machine
       resources :machines do
         resources :service_calls do
         end
       end
     end
   end
   # Admind dashbord
   resources :adminbords do
     # Route to show account
     collection do
       # collect selected accout locations
       get 'select_account_locations/:account_id', to: 'adminbords#select_account_locations', as: 'select_account_locations'
     end
     # Route to Account Index
     get 'accounts', to: 'adminbords#accounts'
   end
   # Locations
   resources :locations do
     get 'contact', to: 'locations#contact'
     ## Machine
     resources :machines do
       resources :service_calls do
       end
     end
  end
  # Machines
   resources :machines do
     resources :service_calls do
     end
   end
   resources :service_calls do
   end


    ## Stand alone routes
   # Route to select a customer to add a new machine
   get 'select_customer_new_machine', to: 'adminbords#select_customer_new_machine'
   # Route to select a customer to add a new locatiom
   get 'select_customer_new_location', to: 'adminbords#select_customer_new_location'
   # Route to select a customer to add a new account
   get 'select_customer_new_account', to: 'adminbords#select_customer_new_account'
   # Route to show account
   get 'adminbords/show_account_register/:account_id', to: 'adminbords#show_account_register', as: 'show_account_register'


   devise_scope :account do
     get 'accounts/registrations/edit_account_register/:id', to: 'accounts/registrations#edit_account_register', as: 'edit_account_register'
     # Routes to
     put 'accounts/registrations/update_account_register/:id', to: 'accounts/registrations#update_account_register', as: 'update_account_register'
     # Routes to
   end

   # Post accounts locations
   post 'adminbords/save_account/:account_id/locations/:selected_locations_ids', to: 'adminbords#save_account_locations', as: 'save_account_locations'

end

app/models/application_helper.rb
module ApplicationHelper
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if resource.class == Admin
      adminbords_path
    elsif resource.class == Accounts
      root_path
    end
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:title, :first_name, :last_name,
      :customer_number, :main_contact, :email, :customer_id])
    devise_parameter_sanitizer.permit(:update, keys: [:title, :first_name, :last_name,
      :customer_number, :main_contact, :email, :customer_id])
  end

end

app/views/application/_footer.html.erb
<!-- Partial rendered by layouts/application.html.erb  -->


<div class="card text-center mt-3">
  <div class="card-header">
  </div>
  <div class="card-body bg-light">
    <h5 class="card-title">Your Document Solutions</h5>
    <%= image_tag 'logo.png', size: "140x55" %>
  </div>
  <div class="card-footer text-muted">
  </div>
</div>

app/views/application/_header.html.erb
<!-- Partial rendered by layouts/application.html.erb -->

<!-- Navigation bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <%= link_to "SCTR", root_path, class: "navbar-brand text-secondery" %>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if account_signed_in?%>
        <li class="nav-item textColorGray mt-2">Hello <%= current_account.first_name %></li>
      <% elsif admin_signed_in?%>
        <li class="nav-item textColorGray mt-2">Hello Admin <%= current_admin.first_name %></li>
      <% end %>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <% if account_signed_in? or admin_signed_in?%>
        <% if account_signed_in?%>
          <%= link_to "Log out", destroy_account_session_path, class: 'nav-link text-dark', method: :delete%>
        <% else %>
          <%= link_to "Dashboard", adminbords_path, class: 'nav-link text-dark' %>
          <%= link_to "Log out", destroy_admin_session_path, class: 'nav-link text-dark', method: :delete%>
        <% end %>
      <% else %>
        <%= link_to "Log in", new_account_session_path, class: 'nav-link text-dark'%>
        <%= link_to "Admin log in", new_admin_session_path, class: 'nav-link text-dark'%>
      <% end %>


      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<% if account_signed_in?%>
  <!-- Customer -->
  <div class="fixed-top mt-5 ml-3">
    <div class="shadow mt-5" style="width: 15rem">
      <ul class="list-unstyled m-0">
        <li><%= link_to "New Service call", customer_location_select_machine_service_path(current_account.customer, current_account.locations), class: 'btn btn  btn-light  w-100' %></li>
        <li><%= link_to "Locations", new_customer_path, class: 'btn  btn-light  w-100' %></li>
        <li><%= link_to "Service calls index", new_customer_path, class: 'btn  btn-light w-100' %></li>
      </ul>
    </div>
  </div>
<% end %>

<% if admin_signed_in?%>
  <!-- Customer -->
<div class="mt-5 ml-5 fixed-top bsize">
  <div class=" mt-5 d-flex flex-column">

    <div class="btn-group mt-1 p">
      <button class="btn btn-large shadow">Customers&#160;&#160;&#160;</button>
      <button class="btn btn-mini dropdown-toggle shadow" data-toggle="dropdown">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu pt-0 pb-0 shadow">
        <li><%= link_to "Index", customers_path, class: 'btn  btn-light w-100' %></li>
        <li><%= link_to "New", new_customer_path, class: 'btn btn-light w-100' %></li>
      </ul>
    </div>
    <div class="btn-group mt-1">
      <button class="btn btn-large shadow">Locations&#160;&#160;&#160;&#160;&#160;</button>
      <button class="btn btn-mini dropdown-toggle shadow" data-toggle="dropdown">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu pt-0 pb-0 shadow">
        <li><%= link_to "Index", locations_path, class: 'btn btn-light w-100' %></li>
        <li><%= link_to "New", select_customer_new_location_path, class: 'btn btn-light w-100' %></li>
      </ul>
    </div>
    <div class="btn-group mt-1">
      <button class="btn btn-large shadow">Machines&#160;&#160;&#160;&#160;&#160;</button>
      <button class="btn btn-mini dropdown-toggle shadow" data-toggle="dropdown">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu pt-0 pb-0 shadow">
        <li><%= link_to "Index", machines_path, class: 'btn btn-light w-100' %></li>
        <li><%= link_to "New", select_customer_new_machine_path, class: 'btn btn-light w-100' %></li>
      </ul>
    </div>
    <div class="btn-group mt-1">
      <button class="btn btn-large shadow">Accounts&#160;&#160;&#160;&#160;&#160;</button>
      <button class="btn btn-mini dropdown-toggle shadow" data-toggle="dropdown">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu pt-0 pb-0 shadow">
        <li><%= link_to "Index", adminbord_accounts_path(1), class: 'btn btn-light w-100' %></li>
        <li><%= link_to "New",select_customer_new_account_path, class: 'btn btn-light w-100' %></li>
    </div>
    <div class="btn-group mt-1">
      <button class="btn btn-large shadow">Service calls</button>
      <button class="btn btn-mini dropdown-toggle shadow" data-toggle="dropdown">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu pt-0 pb-0 shadow">
        <li><%= link_to "Index", service_calls_path, class: 'btn btn-light w-100' %></li>
        <li><%= link_to "Delete", service_calls_path, class: 'btn btn-light w-100' %></li>
      </ul>
    </div>
  </div>
</div>
<% end %>