config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  ## Devise routes modifed to match generated folder with scope
  # Admin
   devise_for :admins, path: 'admins', controllers: {
     sessions: "admins/sessions",
     passwords: "admins/passwords",
     registrations: "admins/registrations",
     confirmations: "admins/confirmations"
   }
   # Account
   devise_for :accounts, path: 'accounts', controllers: {
     sessions: "accounts/sessions",
     passwords: "accounts/passwords",
     registrations: "accounts/registrations",
     confirmations: "accounts/confirmations"
   }

  ## Home page
  root "webpages#index"

   ## Customer
   resources :customers do
     # Route to Customer main contact
     get 'main_contact', to: 'customers#main_contact'
     # Route to select a location before creating a machine
     get 'select_location', to: 'customers#select_location'
     resources :locations do
       get 'contact', to: 'locations#contact'
       get 'select_machine_service', to: 'locations#select_machine_service'
       ## Machine
       resources :machines do
         resources :service_calls do
         end
       end
     end
   end
   # Admind dashbord
   resources :adminbords do
     # Route to show account
     collection do
       # collect selected accout locations
       get 'select_account_locations/:account_id', to: 'adminbords#select_account_locations', as: 'select_account_locations'
     end
     # Route to Account Index
     get 'accounts', to: 'adminbords#accounts'
   end
   # Locations
   resources :locations do
     get 'contact', to: 'locations#contact'
     ## Machine
     resources :machines do
       resources :service_calls do
       end
     end
  end
  # Machines
   resources :machines do
     resources :service_calls do
     end
   end
   resources :service_calls do
   end


    ## Stand alone routes
   # Route to select a customer to add a new machine
   get 'select_customer_new_machine', to: 'adminbords#select_customer_new_machine'
   # Route to select a customer to add a new locatiom
   get 'select_customer_new_location', to: 'adminbords#select_customer_new_location'
   # Route to select a customer to add a new account
   get 'select_customer_new_account', to: 'adminbords#select_customer_new_account'
   # Route to show account
   get 'adminbords/show_account_register/:account_id', to: 'adminbords#show_account_register', as: 'show_account_register'


   devise_scope :account do
     get 'accounts/registrations/edit_account_register/:id', to: 'accounts/registrations#edit_account_register', as: 'edit_account_register'
     # Routes to
     put 'accounts/registrations/update_account_register/:id', to: 'accounts/registrations#update_account_register', as: 'update_account_register'
     # Routes to
   end

   # Post accounts locations
   post 'adminbords/save_account/:account_id/locations/:selected_locations_ids', to: 'adminbords#save_account_locations', as: 'save_account_locations'

end

app/models/adminbord.rb
class Adminbord < ApplicationRecord
  
end

app/controllers/adminbords_controller.rb
class AdminbordsController < ApplicationController

  ###----- Before actions          Append a callback before actions
  ### condition.before_action if condition is true
  ###  set what actions can be call before using all or some CRUD functions
  before_action :authenticate_admin!, only: [:index, :select_customer_new_location, :select_customer_new_machine,
      :select_customer_new_account, :show_account_register]
  before_action :set_customer, only: [:select_customer_new_location, :select_customer_new_machine,
    :select_customer_new_account]
  before_action :set_account, only: [:select_account_locations, :show_account_register, :edit_account_register]

  def index
  end

  def select_customer_new_location
  end

  def select_customer_new_machine
  end

  def select_customer_new_account
  end

  def show_account_register
  end

  def accounts
    @accounts = Account.order(:customer_number).page params[:page]
  end

  def select_account_locations
    customer = Customer.find_by customer_number: @account.customer_number
    locations = customer.locations
    @locations = locations.order(:customer_number).page params[:page]
  end

  def save_account_locations
    account = Account.find(params[:account_id])
    unless (params[:selected_location_ids]) == nil
      locations = Location.find(params[:selected_location_ids])
      account.locations << locations
      # locations .each do |location|
      #   account.locations << location
      # end
      redirect_to show_account_register_path(account)
    else
      redirect_to select_account_locations(account)
    end
  end

private

    def set_customer
      @customers = Customer.order(:customer_number).page params[:page]
    end

    def set_account
      @account = Account.find(params[:account_id])
    end

    def account_params
      params.require(:account).permit(:customer_number, :email, :title, :first_name, :last_name, :encrypted_password,
        :reset_password_token,
        :remember_created_at, :sign_in_count, :current_sign_in_at, :last_sign_in_at, :ast_sign_in_ip,
        :created_at, :updated_at, :customer_id)
    end

end

app/views/adminbords/accounts.html.erb
<!-- account Index -->

  <h1 class="card-header shadow-sm">Account Index</h1>
  <%= paginate @accounts %>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">Customer#</th>
        <th scope="col">Customer Name</th>
        <th scope="col">Email</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.customer_number %></td>
        <td><%= account.customer.bus_name %></td>
        <td><%= account.email %></td>
        <td><%= account.first_name %></td>
        <td><%= account.last_name%></td>
        <td><%= link_to "Show", show_account_register_path(account),
          class: "btn-sm btn-info mt-2  p-1"%></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @accounts %>

app/views/adminbords/index.html.erb
<!--
            Admins with permissions lvl-3 or lower are allower to access this page, customer-no
-->

<!--
Form Admin Dashbord
 -->


<h1 class="card-header shadow">Admin dashboard</h1>
<div class="p-3">
<!-- Buffer Block -->
</div>
<div class="d-flex flex-row justify-content-around">
  <!-- Customer -->
  <div class="card shadow" style="width: 18rem">
    <div class="card-header bg-white">
      <h5>Customer</h5>
    </div>
    <ul class="list-unstyled">
      <li><%= link_to "Index", customers_path, class: 'btn btn-light w-100 mt-2 shadow-sm p-2' %></li>
      <li><%= link_to "New", new_customer_path, class: 'btn btn-light w-100 mt-2 shadow-sm p-2' %></li>
    </ul>
  </div>
  <!-- Locations -->
  <div class="card shadow" style="width: 18rem">
    <div class="card-header bg-white">
      <h5>Location</h5>
    </div>
    <ul class="list-unstyled">
      <li><%= link_to "Index", locations_path, class: 'btn btn-light w-100 mt-2 shadow-sm p-2' %></li>
      <li><%= link_to "New", select_customer_new_location_path, class: 'btn btn-light w-100 mt-2 shadow-sm p-2' %></li>
    </ul>
  </div>
  <!-- Machines -->
  <div class="card shadow" style="width: 18rem">
    <div class="card-header bg-white">
      <h5>Machine</h5>
    </div>
    <ul class="list-unstyled">
      <li><%= link_to "Index", machines_path, class: 'btn btn-light w-100 mt-2 shadow-sm p-2' %></li>
      <li><%= link_to "New", select_customer_new_machine_path, class: 'btn btn-light w-100 mt-2 shadow-sm p-2' %></li>
    </ul>
  </div>
  <!-- Customer's accounts -->
  <div class="card shadow" style="width: 18rem">
    <div class="card-header bg-white">
      <h5>Account</h5>
    </div>
    <ul class="list-unstyled">
      <li><%= link_to "Index", adminbord_accounts_path(1), class: 'btn btn-light w-100 mt-2 shadow-sm p-2' %></li>
      <li><%= link_to "New",select_customer_new_account_path, class: 'btn btn-light w-100 mt-2 shadow-sm p-2'  %></li>
    </ul>
  </div>
  <!-- Services call -->
  <div class="card shadow" style="width: 18rem">
    <div class="card-header bg-white">
      <h5>Service Call</h5>
    </div>
    <ul class="list-unstyled">
      <li><%= link_to "Index", service_calls_path, class: 'btn btn-light w-100 mt-2 shadow-sm p-2' %></li>
      <li><%= link_to "Delete", service_calls_path, class: 'btn btn-light w-100  mt-2 shadow-sm p-2' %></li>
    </ul>
  </div>

</div>

app/views/adminbords/select_account_locations.html.erb
<!--
            Admins with permissions lvl-1 or lower are allower to access this page, customer-no
-->

<!--
select location to add to an  account
 -->

<h1 class="card-header shadow-sm">Select Customer's Account Locations</h1>

<div class="card w-50 ">
  <div class="card-body d-flex flex-row justify-content-between ">
    <div>
      <div>
        <h6 class="pt-3 pr-3"><%= @account.customer.bus_name %></h6>
        <h6 class="pr-3">Tel:&#160;<%= @account.customer.phone %></h6>
         <h6 class="pt-3 pr-3"><%=@account.email%></h6>
        <h6 class="pr-3"><%= @account.first_name %> <%= @account.last_name %></h6>
      </div>
    </div>
    <div>
      <h6 class="pt-3 pr-3"><%= @account.customer_number %></h6>
    </div>
  </div>
</div>

<%= paginate @locations %>
<%= form_tag  save_account_locations_path([@account], [:selected_location_ids]), method: :post do %>
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">Customer's number</th>
        <th scope="col">Costomer's name</th>
        <th scope="col">Location's name</th>
        <th scope="col">Contact' name</th>
        <th scope="col">Contact's phone</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <% @locations.each do |location| %>
      <%# @account.locations.each do |acc_location|%>
          <%# if acc_location != location %>
            <tr>
              <td><%= location.customer_number %></td>
              <td><%= location.customer.bus_name %></td>
              <td><%= location.name %></td>
              <td><%= location.contact__first_name %></td>
              <td><%= location.contact_phone%></td>
              <td><%= check_box_tag "selected_location_ids[]", location.id %></td>
            </tr>
          <%# end %>
        <%# end %>
    <% end %>
    </tbody>
  </table>
<%= submit_tag "Add Selected Locations" %>
<% end %>
<%= paginate @locations %>

app/views/adminbords/select_customer.html.erb
<h1 class="card-header">Customer select</h1>
<%= paginate @customers %>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Phone Number</th>
      <th scope="col">Email</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.customer_number %></td>
      <td><%= customer.name %></td>
      <td><%= customer.phone %></td>
      <td><%= customer.email %></td>
      <td><%= link_to "Select", new_customer_location_path(customer),
        class: "btn-sm btn-primary  mt-2  p-1"%></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @customers %>

app/views/adminbords/select_customer_new_account.html.erb
<!--
            Admins with permissions lvl-1 or lower are allower to access this page, customer-no
-->

<!--
select customer to creat a new customer account
 -->

<h1 class="card-header shadow-sm">Customer Select</h1>
<div class="p-3">
<!-- Buffer Block -->
</div>
<%= paginate @customers %>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.customer_number %></td>
      <td><%= customer.bus_name %></td>
      <td><%= customer.phone %></td>
      <td><%= customer.email %></td>
      <td><%= link_to "Select", new_account_registration_path,
        class: "btn-sm btn-info  mt-2  p-1"%></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @customers %>

app/views/adminbords/select_customer_new_location.html.erb
<!--
            Admins with permissions lvl-1 or lower are allower to access this page, customer-no
-->

<!--
select customer to creat a new location
 -->
<h1 class="card-header shadow-sm">Customer Select</h1>
<div class="p-3">
<!-- Buffer Block -->
</div>
<%= paginate @customers %>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.customer_number %></td>
      <td><%= customer.bus_name %></td>
      <td><%= customer.phone %></td>
      <td><%= customer.email %></td>
      <td><%= link_to "Select", new_customer_location_path(customer.id),
        class: "btn-sm btn-info  mt-2  p-1"%></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @customers %>

app/views/adminbords/select_customer_new_machine.html.erb
<!--
            Admins with permissions lvl-1 or lower are allower to access this page, customer-no
-->

<!--
select customer to creat a new machine redirect to select location
 -->
<h1 class="card-header shadow-sm">Customer Select</h1>
<div class="p-3">
<!-- Buffer Block -->
</div>
<%= paginate @customers %>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Phone</th>
      <th scope="col">Email</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.customer_number %></td>
      <td><%= customer.bus_name %></td>
      <td><%= customer.phone %></td>
      <td><%= customer.email %></td>
      <td><%= link_to "Select", customer_select_location_path(customer),
        class: "btn-sm btn-info  mt-2  p-1"%></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @customers %>

app/views/adminbords/show_account_register.html.erb
<!--
                    ACCOUNT SHOW
No account log in need it admin yes
Admins with permissions lvl-2 or lower are allower to access this page, customer-no
-->
<!--
Customer account reg.
-->
<div class="p-2">
<!-- Buffer Block -->
</div>
<h2 class="card-header shadow-sm">Customer Account</h2>
<div class="p-3">
<!-- Buffer Block -->
</div>
<div class="card w-50 shadow">
  <div class="card-body d-flex flex-row justify-content-between ">
    <div>
      <div>
        <h6 class="pt-3 pr-3"><%= @account.customer.bus_name %></h6>
        <h6 class="pt-3 pr-3">Tel:&#160;<%= @account.customer.phone %></h6>
      </div>
    </div>
    <div>
      <h6 class="pt-3 pr-3"><%= @account.customer_number %></h6>
        <%= link_to "Edit", edit_account_register_path(@account), class: 'btn btn-outline-success' %>
    </div>
  </div>
</div>
<!--Account Info -->
<div class="card w-50">
  <h5 class="card-header"></h5>
  <div class="card-body">
    <!-- Name -->
      <div class="d-flex flex-row justify-content-between">
        <div>
          <p class="card-text"><strong>Title:&#160;</strong><%= @account.title %></p>
          <p class="card-text"><strong>First name:&#160;</strong><%= @account.first_name %></p>
          <p class="card-text"><strong>Last name:&#160;</strong><%= @account.last_name %></P>
        </div>
        <!-- Phone and email -->
        <div class="mr-3">
          <p class="card-text"></p>
          <p class="card-text"><strong>Email:&#160;</strong> <%= @account.email %></p>
      </div>
    </div>
  </div><!-- card-body -->
  <%= link_to "Add Location", select_account_locations_adminbords_path(@account), class: 'btn btn-info' %>
</div><!-- card -->
<div class="p-2">
<!-- Buffer Block -->
</div>
<h2 class="card-header shadow-sm">Account's locations</h2>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th scope="col">Customer#</th>
      <th scope="col">Customer Name</th>
      <th scope="col">Location Name</th>
      <th scope="col">Contact</th>
      <th scope="col">Phone</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @account.locations.each do |location| %>
      <tr>
        <td><%= location.customer_number %></td>
        <td><%= location.customer.bus_name %></td>
        <td><%= location.name %></td>
        <td><%= location.contact__first_name %></td>
        <td><%= location.contact_phone%></td>
        <td><%= link_to "Show", location_path(location),
          class: "btn-sm btn-info  mt-2  p-1"%></td>
      </tr>
  <% end %>
  </tbody>
</table>